$(document).ready(function(){
	$('.single-item').slick({
		dots: true,
		infinite: true,
		speed: 300,
		slidesToShow: 1,
		slidesToScroll: 1,
		arrows: true
	});
	$('.multiple-items').slick({
		dots:true,
		infinite:true,
		speed:300,
		slidesToShow:3,
		slidesToScroll:3
	});
	$('.responsive').slick({
		dots:true,
		infinite:false,
		speed:300,
		slidesToShow:4,
		slidesToScroll:4,
		responsive:[{
			breakpoint:1024,
			settings:{
				slidesToShow:3,
				slidesToScroll:3,
				infinite:true,
				dots: true
			}
		},{
			breakpoint:600,
			settings:{
				slidesToShow:2,
				slidesToScroll:2
			}

		},{
			breakpoint:480,
			settings:{
				slidesToShow:1,
				slidesToScroll:1
			}
		}]
	});
	$('.one-time').slick({
		dots:true,
		infinite:false,
		placeholders:false,
		speed:300,
		slidesToShow:5,
		touchMove:false,
		slidesToScroll:1
	});
	$('.uneven').slick({
		dots:true,
		infinite:true,
		speed:300,
		slidesToScroll:4,
		slidesToShow:4
	});
	$('.center').slick({
		centerMode:true,
		centerPadding:'60px',
		slidesToShow:3,
		autoplay:true,
		autoplaySpeed:3000,
		responsive:[{
			breakpoint:768,
			settings:{
				arrows:false,
				centerMode:true,
				centerPadding:'40px',
				slidesToShow:3
			}
		},{
			breakpoint:400,
			settings:{
				arrows:false,
				centerMode:true,
				centerPadding:'40px',
				slidesToShow:1,
				autoplay:true,
				autoplaySpeed:3000
			}
		}]		
	});
	$('.lazy').slick({
		lazyLoad:'ondemand',
		slidesToShow:3,
		slidesToScroll:1
	});
});